apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: calendar
spec:
  template:
    serviceAccountName: argo
  calendar:
    example-with-interval:
      # creates an event every 30 seconds
      interval: 5m

    example-with-schedule:
      schedule: "35 14 * * *"
      timezone: "Europe/Amsterdam"
      persistence: 
        catchup:
          enabled: true
          maxDuration: "8h"
        configMap:
          name: persistenceconfig
          createIfNotExist: true