apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - calendar-event.yaml
  - nats-trigger.yaml
  - slack-trigger.yaml
  - ./workflow/workflow-minimal.yaml
  - ./nats/deployment.yaml
  - ./nats/service.yaml

secretGenerator:
  - name: slack-secret
    envs:
      - .env.secret
